### PR TITLE
Init

### PR DESCRIPTION
**Pull request by xh3b4sd**
Our libraries to manage Vault primitives are a bit messy. I try to restructure this to be useful for host cluster bootstrapping (via certctl), for certificate generation (via cluster-service) and for PKI backend management and certificate generation (via cert-operator). This lib intends to manage the role part. 

See also 

- https://github.com/giantswarm/vaultcrt/pull/1
- https://github.com/giantswarm/vaultpki/pull/1

### CODE REVIEW

**Comment by xh3b4sd** [comment]
> could be two commands of the same binary

There are no binaries. We have this business logic in `certctl` at the moment and we import a command line tool to use its business logic in our microservices/operators. I want to have common libraries and put the logic into separate repos.

**Comment by kopiczko** [comment]
Understood, why not a single library then?

**Comment by xh3b4sd** [comment]
> why not a single library then?

Lack of cool names.

**Comment by xh3b4sd** [comment]
I am going with this now as a first step. The library was used by the refactored `cert-operator` for over a week now on `gauss`, `ginger` and `lycan`.

**Pull request merged**
